module.exports = {
  DELIVERY_FEE: Number(process.env.DELIVERY_FEE) || 2000,

  ORDER_STATUS: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    PROCESSING: "PROCESSING",
    ASSIGNED: "ASSIGNED",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
    FAILED: "FAILED",
    REFUNDED: "REFUNDED",
  },

  USER_ROLES: {
    ADMIN: "ADMIN",
    STAFF: "STAFF",
    DELIVERY: "DELIVERY",
    CUSTOMER: "CUSTOMER",
  },

  PAYMENT_STATUS: {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    REFUNDED: "REFUNDED",
  },

  PAYMENT_METHODS: {
    MOBILE_MONEY: "MOBILE_MONEY",
    ORANGE_MONEY: "ORANGE_MONEY",
    CASH_ON_DELIVERY: "CASH_ON_DELIVERY",
  },
};
